/**
 * rapidhere@gmail.com
 * Copyright (c) 1995-2017 All Rights Reserved.
 * ===> GLORY TO THE FIRST BORN! <===
 */
package ranttu.rapid.jsvm.jscomp.comp;

import ranttu.rapid.jsvm.codegen.ClassNode;
import ranttu.rapid.jsvm.jscomp.ast.AbstractSyntaxTree;

import java.util.Map;

/**
 * the compiling context
 *
 * @author rapidhere@gmail.com
 * @version $id: CompilingContext.java, v0.1 2017/4/6 dongwei.dq Exp $
 */
public class CompilingContext {
    /** the file name of source*/
    public String                 sourceFileName;

    /** the compiled classname*/
    public String                 className;

    /** the ast */
    public AbstractSyntaxTree     ast;

    //~~~ generated by CollectNamePass
    public NamingEnvironment      namingEnv;

    //~~~ generated by IrTransformPass
    /** ir */
    public ClassNode              rootClassNode;

    //~~~ generated by GenerateByteCodePass
    public Map<String, byte[]>    byteCodes;
}
